package br.edu.ufrn.shipping.saga.choreography.event;

public enum EventType {
    ORDER_CREATED,
    ORDER_CANCELLED,
    ORDER_FINISHED,
    PRODUCT_RESERVED,
    PRODUCT_UNAVAILABLE,
    PRODUCT_RETURNED,
    PAYMENT_CHARGED,
    PAYMENT_REFUSED,
    PAYMENT_REFUNDED,
    SHIPPING_ACCEPTED,
    SHIPPING_REFUSED
}
